/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PastRouteImport } from './routes/past'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as EventEventIdRouteImport } from './routes/event/$eventId'
import { Route as EventCreateRouteImport } from './routes/event/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastRoute = PastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventCreateRoute = EventCreateRouteImport.update({
  id: '/event/create',
  path: '/event/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/past': typeof PastRoute
  '/upcoming': typeof UpcomingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/create': typeof EventCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/past': typeof PastRoute
  '/upcoming': typeof UpcomingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/create': typeof EventCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/past': typeof PastRoute
  '/upcoming': typeof UpcomingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/create': typeof EventCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/past'
    | '/upcoming'
    | '/login'
    | '/register'
    | '/event/$eventId'
    | '/event/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/past'
    | '/upcoming'
    | '/login'
    | '/register'
    | '/event/$eventId'
    | '/event/create'
  id:
    | '__root__'
    | '/'
    | '/past'
    | '/upcoming'
    | '/_auth/login'
    | '/_auth/register'
    | '/event/$eventId'
    | '/event/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PastRoute: typeof PastRoute
  UpcomingRoute: typeof UpcomingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EventEventIdRoute: typeof EventEventIdRoute
  EventCreateRoute: typeof EventCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/create': {
      id: '/event/create'
      path: '/event/create'
      fullPath: '/event/create'
      preLoaderRoute: typeof EventCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PastRoute: PastRoute,
  UpcomingRoute: UpcomingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EventEventIdRoute: EventEventIdRoute,
  EventCreateRoute: EventCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
